[project]
name = "retailaimultiagentsystem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "scikit-learn>=1.8.0",
    "torch>=2.2.2 ; platform_machine != 'x86_64' or sys_platform != 'darwin'",
    "torch<=2.2.2 ; platform_machine == 'x86_64' and sys_platform == 'darwin'",
    "xgboost>=3.2.0",
    "ipykernel>=7.2.0",
]
